name: Build Info

on:
  push:
  workflow_dispatch:

jobs:
  info_job:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4
      
      - name: Wypisanie zawartosci
        run: ls -la
      
      - name: Instalacja Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Sprawdzenie wersji Node.js
        run: node --version