name: Zmienne i Konteksty

on:
  push:
  workflow_dispatch:

env:
  GREETING: "Czesc z Actions"

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
        run: echo "$GREETING / autor ${{ github.actor }} / event ${{ github.event_name }} / sha ${{ github.sha }}"
        
        id: stamp
        run: echo "time=$(date +%s)" >> $GITHUB_OUTPUT
        
        run: echo "Znacznik ${{ steps.stamp.outputs.time }}"